### ISSUE TITLE
Add the ability to run zipped ROMs

### ISSUE THREAD

**Issue by Abzac** [FunKey-Project/FunKey-OS#1]
Add the ability to run zipped ROMs, just like plenty of classic PC emulators do. Maybe, ZIP, RAR, 7z file extensions too (as lots of ROMs are originally distributed in these formats). It would save much space a little. For example, archived GBC ROM is usually less than 100 Kilobytes, and while unpacked it's around a megabyte.
So, it would be convenient to download and run the zipped archive as it is. plus it would save space (although, 32 GiB of FunKey S is roomy, but still)

**Comment by Drumaster78** [comment]
That's because the .desktop files in emulator opks do not all have .zip extensions specified inside. Not sure why they "forgot" to put that. That's easily fixed if you edit your emulator opks in your "Emulators" folder though.

**Comment by hxhieu** [comment]
I can confirm it works (at least for the 3 I tried NES, SNES and GBA), just update the .desktop files and repack the OPK BUT they only work on GMENU2X launcher...
@Drumaster78 have you got any idea how to make RetroFE sees the zips too?

**Comment by Drumaster78** [comment]
I don't know RetroFE and I don't see any setting we can tweak on the fat32 partition of the FunKey S for RetroFE, unlike GMenux2X. That would require editing some files on the Linux partition, if that's not hardcoded of course.

**Comment by hxhieu** [comment]
I think I've found it, yes it's in the Linux partition so look like we need to rebuild the OS or at least if we can SSH in
https://github.com/FunKey-Project/FunKey-OS/blob/master/FunKey/board/funkey/rootfs-overlay/usr/games/collections/NES/settings.conf#L4
@Drumaster78 Do you know how to SSH in via USB? The doc page is blank and I have opened an issue over but no responses yet...
https://github.com/FunKey-Project/FunKey-Project.github.io/issues/5

**Comment by Drumaster78** [comment]
I don't know no. I found the file in "FunKey-sdcard-2.0.0.img" too, The easiest way I think is to remove the micro sd card from your FunKey S then edit settings.conf directly from the Linux partition.
