### ISSUE TITLE
[Recovery] Inconsistent and misleading wording in the menu

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#14]
Wording is inconsistent and misleading in Recovery menu. Indeed "FIRST BOOT DISABLE" is by default and means here that it's disabled and that you have to click to enable it. Regarding "FACTORY TESTS ENABLE" it's the contrary: it's here disabled too and you have to click to enable it whereas the wording is the opposite, that's very confusing and we should differentiate the state of an option and the action it performs when clicking it. As an example, I myself misclicked one or two times and triggered the FIRST BOOT sequence by mistake.
Tested on firmwares 2.0.0, 2.0.1, 2.1.0, 2.1.1 beta, 2.2.0 beta.

1. Press Fn+START while booting the device
2. Once in Recovery menu, use UP or DOWN d-pad to select menu
3. Notice the the inconsistency between "FACTORY TESTS ENABLE", "FIRST BOOT DISABLE" and "NETWORK ENABLE"

**Expected behavior**
By default, you should have the different options like this:
ENABLE FACTORY TESTS => DISABLE FACTORY TESTS
ENABLE FIRST BOOT => DISABLE FIRST BOOT
ENABLE NETWORK => DISABLE NETWORK
or
FACTORY TESTS: DISABLED => FACTORY TESTS: ENABLED
FIRST BOOT: DISABLED => FIRST BOOT: ENABLED
NETWORK: DISABLED => NETWORK: ENABLED

Note: I personally prefer the 2nd one, more natural as that's easier to understand the current status of each option.

**Screenshots**
![first_boot_disable](https://user-images.githubusercontent.com/46139740/115834816-e947d700-a415-11eb-81e1-5e6939a3372d.png) ![factory_tests_enable](https://user-images.githubusercontent.com/46139740/115834821-ea790400-a415-11eb-83b1-483a0c8ce1da.png)

**Comment by Michel-FK** [comment]
The second option is definitely clearer!

**Comment by Michel-FK** [comment]
Corrected with commit https://github.com/FunKey-Project/FunKey-OS/commit/50d8df9895d72b5cc9a8724100e45253bb8c3ba2

**Comment by DrUm78** [comment]
Fixed in verified (I managed to update my "mmcblk0p1" partition without opening my console again)!
