### ISSUE TITLE
[Recovery] Fn+START displays a snapshot confirmation message

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#15]
**Describe the bug**
In Recovery mode, Fn+START key combination (instead of Fn+UP) displays a snapshot confirmation message whereas it does not save it anywhere.
Tested on firmwares 2.0.0, 2.0.1, 2.1.0, 2.1.1 beta, 2.2.0 beta.

**To Reproduce**
1. Press Fn+START when booting the device
2. Once in Recovery mode, press Fn+START
3. Notice that it notifies the user about a new snapshot
4. Mount the USB and go to /mnt/FunKey/snapshots
5. Notice that no snapshots were saved

**Expected behavior**
I guess this command is not intended to work as the snapshot app may not ne loaded yet (TBC), so we should deactivate it or implement properly the snapshot command with Fn+UP and save the pic into its destination (/mnt/FunKey/snapshots).

**Screenshot**
![recovery_snapshots](https://user-images.githubusercontent.com/46139740/115838585-21511900-a41a-11eb-942b-21e73f9a32e8.png)

**Comment by DrUm78** [comment]
BTW a typo is in /usr/local/sbin/snap (see screenshot above): notif_set 2 "   SCREEENSHOT ${snapshot_file}"
Should be: notif_set 2 "   SCREENSHOT ${snapshot_file}"

**Comment by Michel-FK** [comment]
> BTW a typo is in /usr/local/sbin/snap (see screenshot above): notif_set 2 " SCREEENSHOT ${snapshot_file}"
> Indeed there is "SCREEENSHOT" instead of "SCREENSHOT".

Fixed typo in commit https://github.com/FunKey-Project/FunKey-OS/commit/83519eeedb6b8dc98b69488181669426b7c8530d, but cannot reproduce the bug in 2.2.0.

**Comment by DrUm78** [comment]
Really strange, the bug is really easy to reproduce on any firmware, I wonder why you cannot. But anyway, that's a VERY minor thing, no need to spend much time on that I think.

**Comment by DrUm78** [comment]
@Michel-FK I figured out that you need to have "snap" file into "/usr/local/sbin" in "mmcblk0p1" partition (Recovery) to reproduce the bug with FN+START, the bug isn't there if you have "snapshot" instead. Anyway, that's minor and fixed with the "snapshot" file, but still very strange.
