### ISSUE TITLE
[Keymap] Instant Play restores default key mapping

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#17]
Instant Play restores default key mapping after closing and opening the console lid, custom key mapping is not saved.

**Steps to reproduce the behavior:**
1. Launch a rom with a custom key mapping (.key file)
2. Close your console lid
3. Open it again
4. Notice that the default key mapping has been restored

**Expected behavior**
Instant Play feature should load back the custom key mapping.

**Comment by Michel-FK** [comment]
Fixed with commit https://github.com/FunKey-Project/FunKey-OS/commit/240b8fea15fd6b17e4c10bea9bb829564cf715a0

**Comment by DrUm78** [comment]
Fixed and verified!
