### ISSUE TITLE
[Keymap] UNMAP command does not work properly for key combination

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#18]
UNMAP command does not work properly for key combination. Indeed, when trying a "UNMAP FN+L+R" it actually unbinds FN+L+R combination but also all those keys pressed separately.

**Steps to reproduce the behavior:**
1. Launch a rom with a custom key mapping (.key file) with "UNMAP FN+L+R" for instance
2. Notice that now all those 3 keys do not work even when pressed separately

**Expected behavior:**
"UNMAP FN+L+R" command should only block this key combination, not all those 3 keys pressed separately.

**Comment by DrUm78** [comment]
Syntax is simply "UNMAP FN+L+R" (nothing should come after) so that works. Bug closed.

**Comment by Michel-FK** [comment]
Fixed with commits 2d764e398abb2cdf81843b0465d3b0dc498a1109

**Comment by DrUm78** [comment]
Fixed and verified!
