### ISSUE TITLE
[Regression] Changing the launcher with "SET LAUNCHER" option does not load the new launcher

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#25]
Changing the launcher with "SET LAUNCHER" option does not load the new launcher but brings the user back to the current one.
This bug only occurs with an OS built from the develop branch, so it does not impact 2.2.0 users. A system restart loads the new launcher though. Seems related to the commit https://github.com/FunKey-Project/FunKey-OS/commit/961e7dbf24ae4096a60db4d986e97e80e4601d97 which introduced the use of /.frontend file instead of /Launchers/launcher.txt

1. Build an OS from develop branch (commit https://github.com/FunKey-Project/FunKey-OS/commit/4b519d9911417c5f0f2d1571052ce8c2bed5619d)
2. From GMenu2X, open FK menu with MENU key and select "SET LAUNCHER RETROFE"
3. Notice that it brings you back to GMenu2X instead of RetroFE

**Expected behavior**
"SET LAUNCHER" should load the selected launcher.

**Comment by Michel-FK** [comment]
Fixed in commit cefbb58

**Comment by DrUm78** [comment]
Bug fixed and verified, thanks Michel!
