### ISSUE TITLE
Stereo audio isn't downmixed, only the left channel plays

### ISSUE THREAD

**Issue by ghalfacree** [FunKey-Project/FunKey-OS#3]
**Describe the bug**
The FunKey S only has a single speaker, wired to the left audio channel. For monaural games, that's fine; for stereo games, it's a problem. Try playing Sonic The Hedgehog on the Genesis, for example: you'll only hear every other ring pickup sound, because it alternates between the left and right channels. Likewise, music sounds strange because anything which plays on the right channel is missing.

**To Reproduce**
1. Load a game with stereo sound like Sonic the Hedgehog on Genesis.
2. Trigger the stereo sound: for Sonic, collect rings.
3. Listen to the audio that plays.

**Expected behavior**
You hear a ring pickup sound for every ring picked up.

**Actual behavior**
You only hear half the ring pickup sounds - the ones in the left channel.

**Proposed fix**
Short of adding a second speaker to the FunKey S, the fix for this problem would be to downmix stereo audio to mono before sending it to the speaker - ensuring that all audio, not just the left channel, is played. 

This is relatively simple in alsa's ```asound.rc``` configuration file:

```
pcm.!default monodownmix

pcm.monodownmix {
    type route
    slave.pcm "hw:0"
    ttable {
        0.0 1    # in-channel 0, out-channel 0, 100% volume
        1.0 1    # in-channel 1, out-channel 0, 100% volume
    }
}
```

**Comment by Drumaster78** [comment]
I noticed this issue as well. Really something to fix. May be fixed by setting mono sound in each emulator setting file.

**Comment by Drumaster78** [comment]
Setting PD in mono breaks Sega-CD sound though (pitch is very low). Please fix stereo not being downmixed then. :)

**Comment by ghalfacree** [comment]
@Drumaster78 Totally off-topic, but how are you running Sega CD/Mega CD titles on the FunKey? I've got a bunch in BIN/CUE format, but it won't see them.

**Comment by Drumaster78** [comment]
Because .cue file extension has to be added in the .desktop file in emulator opks in "/Emulators" folder. You can edit them with [](https://github.com/Harteex/OpenPackageCreator/releases). You need bios file too for those 2 systems:
For Sega-CD => *.bin file(s) in /FunKey/.picodrive
For PCE CD-Rom => "syscard3.pce" in /FunKey/.mednafen

**Comment by Drumaster78** [comment]
@ghalfacree This commit fixes the issue, I tested it myself :
https://github.com/FunKey-Project/FunKey-OS/commit/32d005f84ec360b27373a39cee31251a295af7a3
