### ISSUE TITLE
UTF-8 support?

### ISSUE THREAD

**Issue by dogboydog** [FunKey-Project/FunKey-OS#33]
**Is your feature request related to a problem? Please describe.**

We noticed that even using a font with East Asian character support, the Funkey will display kanji  and kana as  `?`  in RetroFe and Gmenu2x. 

gameblabla noticed that the partition seems to be  mounted with iso8859-1 encoding. Is there a technical reason why UTF-8 could not be used? Or would it not be possible to change this on a firmware update if the partitions have already been created?

https://github.com/FunKey-Project/FunKey-OS/blob/484d4e690515b89ce967b6d2a151d34b2fdadc92/FunKey/board/funkey/rootfs-overlay/etc/fstab

**Describe the solution you'd like**
If possible, utf-8 support could add support to display more languages.

**Comment by DrUm78** [comment]
AFter a few tries, setting "iocharset=utf8" (seems to be the correct syntax) does not work as GMenu2X simply refuses to boot, then the OS fallbacks on RetroFE which then can not display any rom name if Asian characters are used.

**Comment by dogboydog** [comment]
Yeah I also tested that around when I opened this issue but wasn't sure if something would need to be changed about the flashing or other parts of the firmware to make it work. For me if I recall, RetroFE showed all emulators but all of them had no games and Gmenu2X didn't work like you're saying.

**Comment by DrUm78** [comment]
Yes exactly, something else needs to be done here to support UTF-8, dunno what for now.

**Comment by DrUm78** [comment]
Anyway none of the fonts available on the FunKey S in "/usr/share/fonts" seems to support those extra characters but still, that should not crash. 🤔

**Comment by dogboydog** [comment]
I have a theme I'm working on with a font with UTF-8 support, but I think themes alao didn't work when I changed the charset

**Comment by DrUm78** [comment]
I fixed it in https://github.com/DrUm78/FunKey-OS/commit/30a05af25599ade2e4df30aae8c721d834f0334b but seems like that only GMenu2X supports UTF-8 though. Will investigate further (I asked Slaminger who is a RetroFE dev) but I think it needs support from the RetroFE team or maybe the FK team can do it.

**Comment by haveanair1** [comment]
Can't you just share the image you built for multilingual gmenu2x? Please.

**Comment by DrUm78** [comment]
https://github.com/DrUm78/FunKey-OS/releases/tag/FunKey-OS-2.3.1-DrUm78

@dogboydog As we won't have the fix for RetroFE (needs quite a lot of work and that's on the RetroFE team side), I think we can close the ticket.
