### ISSUE TITLE
When you insert a ROM with a game name in a foreign language other than English, the name is all garbled.

### ISSUE THREAD

**Issue by haveanair1** [FunKey-Project/FunKey-OS#40]
When you insert a ROM with a game name in a foreign language other than English, the name is all garbled. Many Asians who love Funky S are experiencing inconvenience. For example, it would be nice to be able to support multiple languages such as Japanese, Korean, etc. Please let the developers know what you think. Could you please patch it to support UTF-8?

**Comment by DrUm78** [comment]
Known issue, already reported here: https://github.com/FunKey-Project/FunKey-OS/issues/33.

**Comment by DrUm78** [comment]
I fixed it in https://github.com/DrUm78/FunKey-OS/commit/30a05af25599ade2e4df30aae8c721d834f0334b but seems like that only GMenu2X supports UTF-8 though. Will investigate further (I asked one RetroFE's dev) but I think it needs support from the RetroFE team or maybe the FK team can do it.

**Comment by DrUm78** [comment]
Please c;lose the ticket as it's a duplicate of https://github.com/FunKey-Project/FunKey-OS/issues/33.

**Comment by haveanair1** [comment]
edit fstab? "iocharset=utf8,shortname=mixed,errors=remount-ro" ?I have modified the contents, but the conversion to gmenu2x does not work. and I want to edit "FunKey/board/funkey/linux.config" where is it?

**Comment by DrUm78** [comment]
Both etc/fstab and FunKey/board/funkey/linux.config in the OS source files then you need to compile a new OS.

**Comment by haveanair1** [comment]
It would be nice if only gmenu2x could do it. Could you please share the image you built in UTF-8? I'm very sorry to ask.

**Comment by DrUm78** [comment]
Sure, I published a release actually:
https://github.com/DrUm78/FunKey-OS/releases/tag/FunKey-OS-2.3.1-DrUm78
If that's ok for you, please close the ticket. :)

**Comment by haveanair1** [comment]
OMG!! thank you so so so very much!!!  happy new year!!
