### ISSUE TITLE
[Brightness] GMenu2X and FunKey overlay do not use the same setting.

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#5]
GMenu2X and FunKey overlay do not use the same setting, which leads to some conflict between those 2 values (pressing "Start" to display GMenu2X serttings will restore the brightness to GMenu2X value).

Steps to reproduce:
1. Set brightness value to 5 for instance in GMenu2x (Start button)
2. Press Start to exit GMenu2x settings
3. Use Menu button to modify brightness or Fn+X/B shortcut
4. Press Start key twice (open/close Gmenu2X menu)
5. Notice that brightness state is now restored to GMenu2X previous value

Expected behavior:
The brightness value should be shared between GMenu2X and the Funkey overlay and both should impact the other.

**Comment by makergamer** [comment]
Under `/sys/class/backlight/` there should be the "VIDEO" device directories with `brightness` and `max_brightness` therein. 

Knowing that, it should be possible to (using shell examples) :  
`current_brightness = $(cat /sys/class/backlight/VIDEODEV/brightness) # for displaying current level`

`[[ $set_brightness -lt $(cat /sys/class/backlight/VIDEODEV/max_brightness) ]] && echo $set_brightness > /sys/class/backlight/VIDEODEV/brightness # to set the level`

So it should likely be feasible for the menu system & EMUs to have consistent Brightness management.

**Comment by Drumaster78** [comment]
Thanks for the suggestion, I was not sure that communication between GMenu2X and the system brightness setting was possible. :)

**Comment by DrUm78** [comment]
I fixed it by disabling the code and removing the option in GMenu2X: https://github.com/DrUm78/gmenu2x/commit/4fc3eed77dd185775d06f0d819ff9755a16e8737

![170232813-91301f8c-3cd6-4075-9d95-755e104c1983](https://user-images.githubusercontent.com/46139740/170235692-3259e1fc-fbe0-4c08-92c7-f8c0dead591c.png)
No need to have 3 places to set brightness (FK shortcuts, FK menu and GMenu2X options).
Now, the brightness stays consistent when entering GMenu2X option menu.
