### ISSUE TITLE
Game Gear buttons in wrong order

### ISSUE THREAD

**Issue by baochan** [FunKey-Project/FunKey-OS#9]
The two action buttons for the Game Gear emulator are reversed (1 is on the right, 2 is on the left/bottom). Correcting this in the FunKey/.mednafen/mednafen-09x.cfg file on the mounted USB drive doesn't help, as the file seems to be reverted once unmounted. 

I think it's as simple as setting

```
gg.input.builtin.gamepad.button1 keyboard 98
gg.input.builtin.gamepad.button2 keyboard 97
```

But I don't know how to get the values to stick. 

Edit: Sorry if this is the wrong place, I don't know which emulator to add this issue to.

**Comment by Drumaster78** [comment]
As GG emulation is handled by Mednafen, this bug should go there: https://github.com/FunKey-Project/mednafen-git/issues
